import IWork from "@/app/types/IWork";

let workList: IWork[] = [
  {
    title: "Nowa strona internetowa Godere.pl + logo",
    category: "logo design, UI/UX, web development",
    imgUrl: "/godere.jpg",
    desc: "asdf",
    client: "personal work",
    myRole: ["ui/ux design", "development"],
    stack: ["angular"],
    gitUrl: "https://github.com/franckyi/basket-maniacs-app",
    liveUrl: "https://francky.works/basket-maniacs",
  },
  {
    title: "Daddy's Online Shop",
    category: "Aplikacja webowa",
    imgUrl: "",
    desc: "asdf",
    client: "personal work",
    myRole: ["ui/ux design", "development"],
    stack: ["angular"],
    gitUrl: "https://github.com/franckyi/basket-maniacs-app",
    liveUrl: "https://francky.works/basket-maniacs",
  },
  {
    title: "Basket Maniacs",
    category: "Aplikacja webowa",
    imgUrl: "",
    desc: "asdf",
    client: "personal work",
    myRole: ["ui/ux design", "development"],
    stack: ["angular"],
    gitUrl: "https://github.com/franckyi/basket-maniacs-app",
    liveUrl: "https://francky.works/basket-maniacs",
  },
  {
    title: "Sauber Serwis",
    category: "Aplikacja webowa",
    imgUrl: "",
    desc: "asdf",
    client: "personal work",
    myRole: ["ui/ux design", "development"],
    stack: ["angular"],
    gitUrl: "https://github.com/franckyi/basket-maniacs-app",
    liveUrl: "https://francky.works/basket-maniacs",
  },
  {
    title: "Niimbot",
    category: "Aplikacja webowa",
    imgUrl: "",
    desc: "asdf",
    client: "personal work",
    myRole: ["ui/ux design", "development"],
    stack: ["angular"],
    gitUrl: "https://github.com/franckyi/basket-maniacs-app",
    liveUrl: "https://francky.works/basket-maniacs",
  },
  {
    title: "Classic Meble",
    category: "Aplikacja webowa",
    imgUrl: "",
    desc: "asdf",
    client: "personal work",
    myRole: ["ui/ux design", "development"],
    stack: ["angular"],
    gitUrl: "https://github.com/franckyi/basket-maniacs-app",
    liveUrl: "https://francky.works/basket-maniacs",
  },
  {
    title: "Pamaluk Shop",
    category: "Aplikacja webowa",
    imgUrl: "",
    desc: "asdf",
    client: "personal work",
    myRole: ["ui/ux design", "development"],
    stack: ["angular"],
    gitUrl: "https://github.com/franckyi/basket-maniacs-app",
    liveUrl: "https://francky.works/basket-maniacs",
  },
  {
    title: "Weather Application with live background",
    category: "Aplikacja webowa",
    imgUrl: "",
    desc: "asdf",
    client: "personal work",
    myRole: ["ui/ux design", "development"],
    stack: ["angular"],
    gitUrl: "https://github.com/franckyi/basket-maniacs-app",
    liveUrl: "https://francky.works/basket-maniacs",
  },
  {
    title: "Seconds formatter",
    category: "Aplikacja webowa",
    imgUrl: "",
    desc: "asdf",
    client: "personal work",
    myRole: ["ui/ux design", "development"],
    stack: ["angular"],
    gitUrl: "https://github.com/franckyi/basket-maniacs-app",
    liveUrl: "https://francky.works/basket-maniacs",
  },
  {
    title: "G-BIZ Accounting",
    category: "Aplikacja webowa",
    imgUrl: "",
    desc: "asdf",
    client: "personal work",
    myRole: ["ui/ux design", "development"],
    stack: ["angular"],
    gitUrl: "https://github.com/franckyi/basket-maniacs-app",
    liveUrl: "https://francky.works/basket-maniacs",
  },
  {
    title: "Tiffania & Justin",
    category: "Aplikacja webowa",
    imgUrl: "",
    desc: "asdf",
    client: "personal work",
    myRole: ["ui/ux design", "development"],
    stack: ["angular"],
    gitUrl: "https://github.com/franckyi/basket-maniacs-app",
    liveUrl: "https://francky.works/basket-maniacs",
  },
];

export default workList;
